apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-app-deployment
  namespace: mean-frontend
spec:
  selector:
    matchLabels:
      app: resume-app
  template:
    metadata:
      labels:
        app: resume-app
    spec:
      containers:
      - name: resume-app
        image: yashbbhatt/sample-mean-app-frontend:latest
        ports:
        - containerPort: 4200
